[project]
name = "odoo-addons-oca-crm"
version = "18.0.20250204.0"
dependencies = [
    "odoo-addon-crm_lead_firstname==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
